import type { Metadata, Viewport } from "next"
import { Geist_Mono, Instrument_Sans } from "next/font/google"

import "./globals.css"
import { FloatingNav } from "@/components/shared/floating-nav"
import Header from "@/components/shared/header"
import { SwRegister } from "@/components/shared/sw-register"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import { env } from "@/lib/env"
import { APPLE_SPLASH_SCREENS } from "@/lib/splash-screens"
import { cn } from "@/lib/utils"

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
})

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

const BRAND_TITLE = "MyKaggo — Live parcel tracking in Nigeria"

const DESCRIPTION =
  "Track your parcel from departure to destination. MyKaggo gives senders and receivers live visibility over intercity road deliveries across Nigeria."

/**
 * Site-wide metadata.
 *
 * `metadataBase` makes every relative OG/canonical URL absolute, and the title
 * template lets each page contribute only its own name. Private areas opt out
 * of indexing individually rather than here, so the marketing pages stay
 * crawlable.
 */
export const metadata: Metadata = {
  metadataBase: new URL(env.NEXT_PUBLIC_SITE_URL),
  title: {
    default: BRAND_TITLE,
    template: "%s · MyKaggo",
  },
  description: DESCRIPTION,
  applicationName: "MyKaggo",
  keywords: [
    "parcel tracking",
    "package tracking Nigeria",
    "intercity delivery",
    "logistics tracking",
    "MyKaggo",
  ],
  category: "logistics",
  manifest: "/manifest.webmanifest",
  // No `alternates.canonical` here on purpose: metadata is inherited, so a
  // canonical set on the root layout would make every page declare itself a
  // duplicate of "/". Each indexable page sets its own.
  openGraph: {
    type: "website",
    siteName: "MyKaggo",
    title: BRAND_TITLE,
    description: DESCRIPTION,
    url: "/",
    locale: "en_NG",
    images: [
      {
        url: "/images/hero.jpg",
        width: 1200,
        height: 630,
        alt: "MyKaggo parcel tracking",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: BRAND_TITLE,
    description: DESCRIPTION,
    images: ["/images/hero.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  appleWebApp: {
    capable: true,
    title: "MyKaggo",
    // Stays "default": "black-translucent" would let content slide under the
    // status bar and force white status text app-wide, which disappears
    // against the app's light header.
    statusBarStyle: "default",
    /**
     * iOS is the only platform that accepts a supplied launch image; Android
     * composites its own from the manifest icon, `name` and `background_color`.
     * Generated by `npm run splash` from public/images/logo-splashscreen.png.
     */
    startupImage: [...APPLE_SPLASH_SCREENS],
  },
  formatDetection: { telephone: false },
}

export const viewport: Viewport = {
  themeColor: "#008967",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en-NG"
      suppressHydrationWarning
      className={cn(
        "antialiased",
        fontMono.variable,
        "font-sans",
        instrumentSans.variable
      )}
    >
      <body className="bg-muted">
        <ThemeProvider>
          <div className="relative mx-auto flex h-dvh max-w-107.5 flex-col overflow-y-auto bg-background">
            <Header />
            {children}
            <FloatingNav />
            <SwRegister />
          </div>
          <Toaster position="top-center" richColors />
        </ThemeProvider>
      </body>
    </html>
  )
}
